---
- name: Copy MQ Trial from Control to Z Worker
  ansible.builtin.copy:
    src: "{{ mq_local_path }}"
    dest: /var/mq.tar.gz
    mode: "0644"
  when: local_source

- name: Extract MQ fom TAR
  ansible.builtin.unarchive:
    src: /var/mq.tar.gz
    remote_src: true
    dest: /var
  tags: download
  when: local_source
