---
- name: Change owner and permissions on mqwebuser.xml
  become: true
  ansible.builtin.file:
    path: mqwebuser.xml
    owner: mqm
    attributes: u+w

- name: Allow console to be accessed from anywhere
  ansible.builtin.command:
    cmd: setmqweb properties -k httpHost -v "*"
    chdir: /var/mqm/web/installations/Installation1/servers/mqweb
  become: true
  become_user: mqm
  changed_when: true

- name: Start web console
  ansible.builtin.command:
    cmd: nohup strmqweb
    chdir: /var/mqm/web/installations/Installation1/servers/mqweb
  become: true
  become_user: mqm
  changed_when: true

- name: Check if Web Console is Running
  become: true
  become_user: mqm
  ansible.builtin.command:
    cmd: dspmqweb
    chdir: /var/mqm/web/installations/Installation1/servers/mqweb
  changed_when: false
  ignore_errors: true
  register: console_status
  failed_when:
    - console_status.rc != 0
