---
- name: Incrase ssh connection timeout
  ansible.builtin.command: /usr/sbin/sshd -o ClientAliveInterval=3000
  changed_when: true

- name: Increase space on the disk
  ansible.builtin.command: chfs -a size=+4G /tmp
  changed_when: true

- name: Increase max_file
  ansible.builtin.command: huser fsize=-1 root
  changed_when: true
