---
- name: Check if basic registry exists
  ansible.builtin.stat:
    path: /opt/mqm/web/mq/samp/configuration/basic_registry.xml
  register: basic_registry_result

- name: Moving basic registry
  become: true
  ansible.builtin.copy:
    src: /opt/mqm/web/mq/samp/configuration/basic_registry.xml
    dest: /var/mqm/web/installations/Installation1/servers/mqweb/
    remote_src: true
    mode: "{{ basic_registry_result.stat.mode }}"
  when: basic_registry_result.stat.exists

- name: Remove old basic registry
  ansible.builtin.file:
    path: /var/mqm/web/installations/Installation1/servers/mqweb/
    state: absent
  when: basic_registry_result.stat.exists

- name: Check if old mqwebuser exists
  ansible.builtin.stat:
    path: /var/mqm/web/installations/Installation1/servers/mqweb/mqwebuser.old
  register: mqwebuser_result

- name: Stat mqwebuser
  ansible.builtin.stat:
    path: /var/mqm/web/installations/Installation1/servers/mqweb/mqwebuser.xml
  register: mqwebuser_current_result

- name: Moving mqwebuser to old mqwebuser
  become: true
  ansible.builtin.copy:
    src: /var/mqm/web/installations/Installation1/servers/mqweb/mqwebuser.xml
    dest: /var/mqm/web/installations/Installation1/servers/mqweb/mqwebuser.old
    remote_src: true
    mode: "{{ mqwebuser_current_result.stat.mode }}"
  when: not mqwebuser_result.stat.exists

- name: Check if moved basic registry exists
  ansible.builtin.stat:
    path: /var/mqm/web/installations/Installation1/servers/mqweb/basic_registry.xml
  register: moved_registry

- name: Using basic_registry as webwebuser
  become: true
  ansible.builtin.copy:
    src: /var/mqm/web/installations/Installation1/servers/mqweb/basic_registry.xml
    dest: /var/mqm/web/installations/Installation1/servers/mqweb/mqwebuser.xml
    remote_src: true
    mode: "{{ moved_registry.stat.mode }}"
  when: moved_registry.stat.exists

- name: Remove old basic_registry
  ansible.builtin.file:
    path: /var/mqm/web/installations/Installation1/servers/mqweb/basic_registry.xml
    state: absent
  when: moved_registry.stat.exists

- name: Check correct mqwebuser exists
  ansible.builtin.stat:
    path: /var/mqm/web/installations/Installation1/servers/mqweb/mqwebuser.xml
  register: final_mqwebuser

- name: Ensure correct permissions for mqwebuser.xml
  become: true
  ansible.builtin.file:
    path: /var/mqm/web/installations/Installation1/servers/mqweb/mqwebuser.xml
    mode: "0640"
  when: final_mqwebuser.stat.exists
